# A short, descriptive name of this building block collection
name: Building Blocks for Metadata

# Short abstract for this collection (optional)
abstract: |
  Defines a set of Building Blocks for various options for metadata records using OGC standards.   
  These may be combined with application semantics to define specific metadata profiles for application domains. 

# Description for this collection (optional)
description: |
  Most "systems of systems" will have 
  multiple metadata formats in play due to evolution, backwards compatibility requirements and specific metadata needs of different communities and systems.
  
  These Building Blocks provide for common approach to defining, discovering, transforming and validating different metadata models.

# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.model.metadata

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default
  - https://ogcincubator.github.io/geodcat-ogcapi-records/build/register.json
  - https://ogcincubator.github.io/bblocks-stac/build/register.json
  - https://ogcincubator.github.io/bblocks-ogcapi-records/build/register.json
  # to be added - ISO 19115 Part 4 when it emerges

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available